# Time Series Basics

## Importing Time Series Data from csv-Files

In [1]:
import pandas as pd

In [2]:
temp = pd.read_csv("temp.csv", parse_dates = ["datetime"], index_col= "datetime")

In [3]:
temp.head()

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3

In [4]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 35064 entries, 2013-01-01 00:00:00 to 2016-12-31 23:00:00
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LA      35062 non-null  float64
 1   NY      35064 non-null  float64
dtypes: float64(2)
memory usage: 821.8 KB

In [7]:
type(temp.iloc[0, 0])

numpy.float64

In [8]:
temp.index

DatetimeIndex(['2013-01-01 00:00:00', '2013-01-01 01:00:00',
               '2013-01-01 02:00:00', '2013-01-01 03:00:00',
               '2013-01-01 04:00:00', '2013-01-01 05:00:00',
               '2013-01-01 06:00:00', '2013-01-01 07:00:00',
               '2013-01-01 08:00:00', '2013-01-01 09:00:00',
               ...
               '2016-12-31 14:00:00', '2016-12-31 15:00:00',
               '2016-12-31 16:00:00', '2016-12-31 17:00:00',
               '2016-12-31 18:00:00', '2016-12-31 19:00:00',
               '2016-12-31 20:00:00', '2016-12-31 21:00:00',
               '2016-12-31 22:00:00', '2016-12-31 23:00:00'],
              dtype='datetime64[ns]', name='datetime', length=35064, freq=None)

In [9]:
temp.index[0]

Timestamp('2013-01-01 00:00:00')

## Converting strings to datetime objects with pd.to_datetime()

In [10]:
import pandas as pd

In [11]:
temp = pd.read_csv("temp.csv")

In [12]:
temp.head()

              datetime    LA   NY
0  2013-01-01 00:00:00  11.7 -1.1
1  2013-01-01 01:00:00  10.7 -1.7
2  2013-01-01 02:00:00   9.9 -2.0
3  2013-01-01 03:00:00   9.3 -2.1
4  2013-01-01 04:00:00   8.8 -2.3

In [13]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  35064 non-null  object
 1   LA        35062 non-null  float64
 2   NY        35064 non-null  float64
dtypes: float64(2), object(1)
memory usage: 821.9+ KB

In [14]:
temp.datetime[0]

'2013-01-01 00:00:00'

In [15]:
pd.to_datetime(temp.datetime)

0       2013-01-01 00:00:00
1       2013-01-01 01:00:00
2       2013-01-01 02:00:00
3       2013-01-01 03:00:00
4       2013-01-01 04:00:00
                ...
35059   2016-12-31 19:00:00
35060   2016-12-31 20:00:00
35061   2016-12-31 21:00:00
35062   2016-12-31 22:00:00
35063   2016-12-31 23:00:00
Name: datetime, Length: 35064, dtype: datetime64[ns]

In [16]:
temp = temp.set_index(pd.to_datetime(temp.datetime)).drop("datetime", axis = 1)

In [17]:
temp.head()

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3

In [18]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 35064 entries, 2013-01-01 00:00:00 to 2016-12-31 23:00:00
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LA      35062 non-null  float64
 1   NY      35064 non-null  float64
dtypes: float64(2)
memory usage: 821.8 KB

In [19]:
temp.index[0]

Timestamp('2013-01-01 00:00:00')

In [20]:
pd.to_datetime("2015-05-20 10:30:20")

Timestamp('2015-05-20 10:30:20')

In [21]:
pd.to_datetime("20150520")

Timestamp('2015-05-20 00:00:00')

In [22]:
pd.to_datetime("2015/05/20")

Timestamp('2015-05-20 00:00:00')

In [23]:
pd.to_datetime("2015 05 20")

Timestamp('2015-05-20 00:00:00')

In [ ]:
#pd.to_datetime("2015-20-05")

In [24]:
pd.to_datetime("2015 May 20")

Timestamp('2015-05-20 00:00:00')

In [25]:
pd.to_datetime("May 2015 20")

Timestamp('2015-05-20 00:00:00')

In [26]:
pd.to_datetime("2015 20th may")

Timestamp('2015-05-20 00:00:00')

In [ ]:
#pd.to_datetime(["2015-05-20", "Feb 20 2015"]) # old

In [27]:
pd.to_datetime(["2015-05-20", "Feb 20 2015"], format = "mixed") # new

DatetimeIndex(['2015-05-20', '2015-02-20'], dtype='datetime64[ns]', freq=None)

In [28]:
pd.to_datetime(["2015-05-20", "Feb 20 2015", "Elephant"], errors="coerce") # old

DatetimeIndex(['2015-05-20', 'NaT', 'NaT'], dtype='datetime64[ns]', freq=None)

In [29]:
pd.to_datetime(["2015-05-20", "Feb 20 2015", "Elephant"], format = "mixed", errors="coerce") # new

DatetimeIndex(['2015-05-20', '2015-02-20', 'NaT'], dtype='datetime64[ns]', freq=None)

## Indexing and Slicing Time Series

In [30]:
import pandas as pd

In [31]:
temp = pd.read_csv("temp.csv", parse_dates= ["datetime"], index_col= "datetime")

In [32]:
temp.head()

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3

In [33]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 35064 entries, 2013-01-01 00:00:00 to 2016-12-31 23:00:00
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LA      35062 non-null  float64
 1   NY      35064 non-null  float64
dtypes: float64(2)
memory usage: 821.8 KB

In [34]:
temp.loc["2013-01-01 01:00:00"]

LA    10.7
NY    -1.7
Name: 2013-01-01 01:00:00, dtype: float64

In [35]:
temp.loc["2015"]

                       LA   NY
datetime
2015-01-01 00:00:00   3.8 -5.1
2015-01-01 01:00:00   4.4 -5.1
2015-01-01 02:00:00   3.2 -6.0
2015-01-01 03:00:00   1.2 -6.0
2015-01-01 04:00:00   0.2 -6.0
...                   ...  ...
2015-12-31 19:00:00  16.0  8.1
2015-12-31 20:00:00  16.0  8.1
2015-12-31 21:00:00  16.4  7.9
2015-12-31 22:00:00  16.6  7.2
2015-12-31 23:00:00  16.8  6.2

[8760 rows x 2 columns]

In [36]:
temp.loc["2015-05"]

                       LA    NY
datetime
2015-05-01 00:00:00  25.5  13.9
2015-05-01 01:00:00  25.7  13.9
2015-05-01 02:00:00  23.8  10.5
2015-05-01 03:00:00  22.0  10.2
2015-05-01 04:00:00  20.1   8.6
...                   ...   ...
2015-05-31 19:00:00  25.4  25.5
2015-05-31 20:00:00  26.0  23.9
2015-05-31 21:00:00  24.9  22.5
2015-05-31 22:00:00  26.0  21.3
2015-05-31 23:00:00  25.5  19.9

[744 rows x 2 columns]

In [37]:
temp.loc["2015-05-20"].shape

(24, 2)

In [38]:
temp.loc["2015-05-20 10:00:00"]

LA     7.8
NY    13.3
Name: 2015-05-20 10:00:00, dtype: float64

In [ ]:
#temp.loc["2015-05-20 10:30:00"]

In [39]:
temp.loc["2015-01-01" : "2015-12-31"]

                       LA   NY
datetime
2015-01-01 00:00:00   3.8 -5.1
2015-01-01 01:00:00   4.4 -5.1
2015-01-01 02:00:00   3.2 -6.0
2015-01-01 03:00:00   1.2 -6.0
2015-01-01 04:00:00   0.2 -6.0
...                   ...  ...
2015-12-31 19:00:00  16.0  8.1
2015-12-31 20:00:00  16.0  8.1
2015-12-31 21:00:00  16.4  7.9
2015-12-31 22:00:00  16.6  7.2
2015-12-31 23:00:00  16.8  6.2

[8760 rows x 2 columns]

In [40]:
temp.loc["2015-01-01" : "2015-12-31"].equals(temp.loc["2015"])

True

In [41]:
temp.loc["2015-04-15" : "2016-02-23"]

                       LA    NY
datetime
2015-04-15 00:00:00  19.1  12.8
2015-04-15 01:00:00  20.0  12.0
2015-04-15 02:00:00  17.7  11.3
2015-04-15 03:00:00  15.5  11.2
2015-04-15 04:00:00  13.3  10.4
...                   ...   ...
2016-02-23 19:00:00  23.4   2.6
2016-02-23 20:00:00  23.4   2.2
2016-02-23 21:00:00  26.8   2.2
2016-02-23 22:00:00  26.8   2.0
2016-02-23 23:00:00  26.8   2.3

[7560 rows x 2 columns]

In [42]:
temp.loc["2015-05-20":]

                       LA    NY
datetime
2015-05-20 00:00:00  17.7  19.8
2015-05-20 01:00:00  18.0  19.7
2015-05-20 02:00:00  16.6  19.0
2015-05-20 03:00:00  14.4  19.0
2015-05-20 04:00:00  13.3  19.7
...                   ...   ...
2016-12-31 19:00:00  13.5   4.6
2016-12-31 20:00:00  13.2   5.7
2016-12-31 21:00:00  12.8   5.8
2016-12-31 22:00:00  12.3   5.7
2016-12-31 23:00:00  11.9   5.5

[14208 rows x 2 columns]

In [43]:
temp.loc[:"2015-05-20"]

                       LA    NY
datetime
2013-01-01 00:00:00  11.7  -1.1
2013-01-01 01:00:00  10.7  -1.7
2013-01-01 02:00:00   9.9  -2.0
2013-01-01 03:00:00   9.3  -2.1
2013-01-01 04:00:00   8.8  -2.3
...                   ...   ...
2015-05-20 19:00:00  17.7  18.1
2015-05-20 20:00:00  18.4  17.8
2015-05-20 21:00:00  18.0  17.8
2015-05-20 22:00:00  19.1  14.2
2015-05-20 23:00:00  19.1  14.2

[20880 rows x 2 columns]

In [44]:
temp.loc["20FEBRUARY2015"]

                       LA    NY
datetime
2015-02-20 00:00:00  16.4 -12.4
2015-02-20 01:00:00  17.5 -12.4
2015-02-20 02:00:00  14.6 -14.5
2015-02-20 03:00:00  13.9 -14.5
2015-02-20 04:00:00  10.3 -14.5
2015-02-20 05:00:00   8.9 -15.9
2015-02-20 06:00:00   9.0 -15.9
2015-02-20 07:00:00   7.1 -15.9
2015-02-20 08:00:00   6.6 -16.8
2015-02-20 09:00:00   6.3 -16.8
2015-02-20 10:00:00   5.8 -16.8
2015-02-20 11:00:00   5.5 -17.4
2015-02-20 12:00:00   5.8 -17.4
2015-02-20 13:00:00   5.2 -17.4
2015-02-20 14:00:00   5.3 -14.0
2015-02-20 15:00:00  10.5 -14.2
2015-02-20 16:00:00   8.9 -14.0
2015-02-20 17:00:00  12.4 -10.4
2015-02-20 18:00:00  12.0 -10.2
2015-02-20 19:00:00  16.8  -9.9
2015-02-20 20:00:00  17.7  -9.3
2015-02-20 21:00:00  17.2  -9.3
2015-02-20 22:00:00  18.5  -9.3
2015-02-20 23:00:00  18.5 -14.0

In [45]:
temp.loc[["2015-05-20 10:00:00", "2015-05-20 12:00:00"]] # now works

                      LA    NY
datetime
2015-05-20 10:00:00  7.8  13.3
2015-05-20 12:00:00  9.7  13.6

In [46]:
two_timestamps = pd.to_datetime(["2015-05-20 10:00:00", "2015-05-20 12:00:00"])
two_timestamps

DatetimeIndex(['2015-05-20 10:00:00', '2015-05-20 12:00:00'], dtype='datetime64[ns]', freq=None)

In [47]:
temp.loc[two_timestamps]

                      LA    NY
2015-05-20 10:00:00  7.8  13.3
2015-05-20 12:00:00  9.7  13.6

## Downsampling Time Series with resample()

In [48]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")

In [49]:
temp = pd.read_csv("temp.csv", parse_dates= ["datetime"], index_col = "datetime")

In [52]:
temp.head()

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3

In [53]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 35064 entries, 2013-01-01 00:00:00 to 2016-12-31 23:00:00
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LA      35062 non-null  float64
 1   NY      35064 non-null  float64
dtypes: float64(2)
memory usage: 821.8 KB

In [54]:
temp.resample("D")

In [65]:
list(temp.resample("D"))[1][1]

                       LA   NY
datetime
2013-01-02 00:00:00  13.2  2.6
2013-01-02 01:00:00  11.8  2.7
2013-01-02 02:00:00  10.5  2.9
2013-01-02 03:00:00   9.5  2.9
2013-01-02 04:00:00   8.3  2.9
2013-01-02 05:00:00   8.0  3.5
2013-01-02 06:00:00   7.5  3.7
2013-01-02 07:00:00   7.1  3.5
2013-01-02 08:00:00   6.4  3.7
2013-01-02 09:00:00   6.0  3.6
2013-01-02 10:00:00   5.9  3.5
2013-01-02 11:00:00   6.1  3.6
2013-01-02 12:00:00   5.8  3.5
2013-01-02 13:00:00   5.6  3.5
2013-01-02 14:00:00   5.8  3.7
2013-01-02 15:00:00   5.9  4.0
2013-01-02 16:00:00   6.4  4.0
2013-01-02 17:00:00   9.0  3.6
2013-01-02 18:00:00  11.5  3.1
2013-01-02 19:00:00  13.3  3.2
2013-01-02 20:00:00  14.2  3.2
2013-01-02 21:00:00  15.0  2.9
2013-01-02 22:00:00  14.9  2.0
2013-01-02 23:00:00  15.1  1.2

In [56]:
temp.head(25)

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3
2013-01-01 05:00:00   8.7 -2.5
2013-01-01 06:00:00   6.9 -3.2
2013-01-01 07:00:00   7.8 -3.4
2013-01-01 08:00:00   6.7 -3.0
2013-01-01 09:00:00   6.6 -1.8
2013-01-01 10:00:00   6.1 -1.4
2013-01-01 11:00:00   5.6 -1.8
2013-01-01 12:00:00   5.1 -1.7
2013-01-01 13:00:00   5.2 -1.5
2013-01-01 14:00:00   4.6 -1.0
2013-01-01 15:00:00   5.1 -0.0
2013-01-01 16:00:00   6.2  1.2
2013-01-01 17:00:00   9.3  2.2
2013-01-01 18:00:00  11.4  3.3
2013-01-01 19:00:00  12.0  3.5
2013-01-01 20:00:00  12.9  3.1
2013-01-01 21:00:00  13.9  2.4
2013-01-01 22:00:00  14.1  2.4
2013-01-01 23:00:00  14.0  2.7
2013-01-02 00:00:00  13.2  2.6

In [57]:
temp.resample("D").sum()

               LA     NY
datetime
2013-01-01  212.6   -9.7
2013-01-02  222.8   77.0
2013-01-03  247.3  -58.2
2013-01-04  276.3  -49.7
2013-01-05  266.0   19.6
...           ...    ...
2016-12-27  291.7  253.9
2016-12-28  346.4   96.4
2016-12-29  385.1   31.5
2016-12-30  382.4   52.9
2016-12-31  318.6   28.9

[1461 rows x 2 columns]

In [58]:
temp.resample("2h").last() # use h instead of H

                       LA   NY
datetime
2013-01-01 00:00:00  10.7 -1.7
2013-01-01 02:00:00   9.3 -2.1
2013-01-01 04:00:00   8.7 -2.5
2013-01-01 06:00:00   7.8 -3.4
2013-01-01 08:00:00   6.6 -1.8
...                   ...  ...
2016-12-31 14:00:00  13.0 -0.6
2016-12-31 16:00:00  12.9  1.9
2016-12-31 18:00:00  13.5  4.6
2016-12-31 20:00:00  12.8  5.8
2016-12-31 22:00:00  11.9  5.5

[17532 rows x 2 columns]

In [66]:
temp.resample("W").mean()

                   LA        NY
datetime
2013-01-06  10.214583  0.222917
2013-01-13  10.494048  4.245238
2013-01-20  11.119643  3.924405
2013-01-27  15.586905 -4.660714
2013-02-03  11.569643  1.502381
...               ...       ...
2016-12-04  12.975595  8.024405
2016-12-11  13.738095  1.922619
2016-12-18  13.466667  0.052381
2016-12-25  13.007143  1.149405
2017-01-01  13.511806  3.479861

[209 rows x 2 columns]

In [67]:
temp.resample("W-Wed").mean()

                   LA        NY
datetime
2013-01-02   9.070833  1.402083
2013-01-09  11.033333  1.033929
2013-01-16   8.870238  6.001190
2013-01-23  14.678571  1.010714
2013-01-30  12.554762 -4.382738
...               ...       ...
2016-12-07  13.205357  5.964286
2016-12-14  14.490476  1.228571
2016-12-21  13.209524 -2.248810
2016-12-28  11.930357  4.688095
2017-01-04  15.084722  1.573611

[210 rows x 2 columns]

In [68]:
temp.resample("ME").mean() # use ME instead of M

                   LA         NY
datetime
2013-01-31  11.596237   1.129570
2013-02-28  12.587202   0.617857
2013-03-31  15.069946   3.719220
2013-04-30  16.487361  10.699306
2013-05-31  19.005780  15.824328
2013-06-30  19.905417  22.225694
2013-07-31  22.093952  26.329704
2013-08-31  21.513172  22.480376
2013-09-30  22.404861  18.291806
2013-10-31  16.620430  14.335215
2013-11-30  15.107917   7.111944
2013-12-31  13.416935   2.776210
2014-01-31  16.247715  -2.210349
2014-02-28  14.326637  -1.596280
2014-03-31  15.836156   1.994758
2014-04-30  16.783472  10.128611
2014-05-31  20.041398  16.829167
2014-06-30  19.810556  21.784861
2014-07-31  23.056183  24.019624
2014-08-31  22.146102  21.848387
2014-09-30  21.620278  19.267222
2014-10-31  16.968280  14.265860
2014-11-30  11.322083   5.719167
2014-12-31   8.523925   3.513844
2015-01-31   9.527016  -4.179301
2015-02-28  11.587649  -7.239732
2015-03-31  14.465995   1.020161
2015-04-30  13.527917  10.180417
2015-05-31  14.540054  18.731586
2015-06-30  20.995000  20.347500
2015-07-31  22.899059  24.252151
2015-08-31  24.846909  24.046774
2015-09-30  24.586250  21.589861
2015-10-31  21.785753  12.656452
2015-11-30  15.255278  10.117500
2015-12-31  11.919758   8.662500
2016-01-31  12.509274   0.168952
2016-02-29  16.600431   2.069971
2016-03-31  15.686425   8.070430
2016-04-30  17.726111  10.535556
2016-05-31  17.375403  15.874462
2016-06-30  22.536111  21.462639
2016-07-31  24.541532  24.767608
2016-08-31  23.983199  25.351882
2016-09-30  22.379306  21.032778
2016-10-31  16.137903  14.321640
2016-11-30  17.196111   8.539722
2016-12-31  13.390457   2.327285

In [69]:
temp.resample("MS").mean()

                   LA         NY
datetime
2013-01-01  11.596237   1.129570
2013-02-01  12.587202   0.617857
2013-03-01  15.069946   3.719220
2013-04-01  16.487361  10.699306
2013-05-01  19.005780  15.824328
2013-06-01  19.905417  22.225694
2013-07-01  22.093952  26.329704
2013-08-01  21.513172  22.480376
2013-09-01  22.404861  18.291806
2013-10-01  16.620430  14.335215
2013-11-01  15.107917   7.111944
2013-12-01  13.416935   2.776210
2014-01-01  16.247715  -2.210349
2014-02-01  14.326637  -1.596280
2014-03-01  15.836156   1.994758
2014-04-01  16.783472  10.128611
2014-05-01  20.041398  16.829167
2014-06-01  19.810556  21.784861
2014-07-01  23.056183  24.019624
2014-08-01  22.146102  21.848387
2014-09-01  21.620278  19.267222
2014-10-01  16.968280  14.265860
2014-11-01  11.322083   5.719167
2014-12-01   8.523925   3.513844
2015-01-01   9.527016  -4.179301
2015-02-01  11.587649  -7.239732
2015-03-01  14.465995   1.020161
2015-04-01  13.527917  10.180417
2015-05-01  14.540054  18.731586
2015-06-01  20.995000  20.347500
2015-07-01  22.899059  24.252151
2015-08-01  24.846909  24.046774
2015-09-01  24.586250  21.589861
2015-10-01  21.785753  12.656452
2015-11-01  15.255278  10.117500
2015-12-01  11.919758   8.662500
2016-01-01  12.509274   0.168952
2016-02-01  16.600431   2.069971
2016-03-01  15.686425   8.070430
2016-04-01  17.726111  10.535556
2016-05-01  17.375403  15.874462
2016-06-01  22.536111  21.462639
2016-07-01  24.541532  24.767608
2016-08-01  23.983199  25.351882
2016-09-01  22.379306  21.032778
2016-10-01  16.137903  14.321640
2016-11-01  17.196111   8.539722
2016-12-01  13.390457   2.327285

In [ ]:
# temp.resample("MS", loffset="14D").mean() # old

In [70]:
# new (Alt 1)
temp.resample("MS").mean().shift(14, freq="D")

                   LA         NY
datetime
2013-01-15  11.596237   1.129570
2013-02-15  12.587202   0.617857
2013-03-15  15.069946   3.719220
2013-04-15  16.487361  10.699306
2013-05-15  19.005780  15.824328
2013-06-15  19.905417  22.225694
2013-07-15  22.093952  26.329704
2013-08-15  21.513172  22.480376
2013-09-15  22.404861  18.291806
2013-10-15  16.620430  14.335215
2013-11-15  15.107917   7.111944
2013-12-15  13.416935   2.776210
2014-01-15  16.247715  -2.210349
2014-02-15  14.326637  -1.596280
2014-03-15  15.836156   1.994758
2014-04-15  16.783472  10.128611
2014-05-15  20.041398  16.829167
2014-06-15  19.810556  21.784861
2014-07-15  23.056183  24.019624
2014-08-15  22.146102  21.848387
2014-09-15  21.620278  19.267222
2014-10-15  16.968280  14.265860
2014-11-15  11.322083   5.719167
2014-12-15   8.523925   3.513844
2015-01-15   9.527016  -4.179301
2015-02-15  11.587649  -7.239732
2015-03-15  14.465995   1.020161
2015-04-15  13.527917  10.180417
2015-05-15  14.540054  18.731586
2015-06-15  20.995000  20.347500
2015-07-15  22.899059  24.252151
2015-08-15  24.846909  24.046774
2015-09-15  24.586250  21.589861
2015-10-15  21.785753  12.656452
2015-11-15  15.255278  10.117500
2015-12-15  11.919758   8.662500
2016-01-15  12.509274   0.168952
2016-02-15  16.600431   2.069971
2016-03-15  15.686425   8.070430
2016-04-15  17.726111  10.535556
2016-05-15  17.375403  15.874462
2016-06-15  22.536111  21.462639
2016-07-15  24.541532  24.767608
2016-08-15  23.983199  25.351882
2016-09-15  22.379306  21.032778
2016-10-15  16.137903  14.321640
2016-11-15  17.196111   8.539722
2016-12-15  13.390457   2.327285

In [71]:
# new (Alt 2)
from pandas.tseries.frequencies import to_offset
df2 = temp.resample("MS").mean()
df2.index = df2.index + to_offset("14D")
df2

                   LA         NY
datetime
2013-01-15  11.596237   1.129570
2013-02-15  12.587202   0.617857
2013-03-15  15.069946   3.719220
2013-04-15  16.487361  10.699306
2013-05-15  19.005780  15.824328
2013-06-15  19.905417  22.225694
2013-07-15  22.093952  26.329704
2013-08-15  21.513172  22.480376
2013-09-15  22.404861  18.291806
2013-10-15  16.620430  14.335215
2013-11-15  15.107917   7.111944
2013-12-15  13.416935   2.776210
2014-01-15  16.247715  -2.210349
2014-02-15  14.326637  -1.596280
2014-03-15  15.836156   1.994758
2014-04-15  16.783472  10.128611
2014-05-15  20.041398  16.829167
2014-06-15  19.810556  21.784861
2014-07-15  23.056183  24.019624
2014-08-15  22.146102  21.848387
2014-09-15  21.620278  19.267222
2014-10-15  16.968280  14.265860
2014-11-15  11.322083   5.719167
2014-12-15   8.523925   3.513844
2015-01-15   9.527016  -4.179301
2015-02-15  11.587649  -7.239732
2015-03-15  14.465995   1.020161
2015-04-15  13.527917  10.180417
2015-05-15  14.540054  18.731586
2015-06-15  20.995000  20.347500
2015-07-15  22.899059  24.252151
2015-08-15  24.846909  24.046774
2015-09-15  24.586250  21.589861
2015-10-15  21.785753  12.656452
2015-11-15  15.255278  10.117500
2015-12-15  11.919758   8.662500
2016-01-15  12.509274   0.168952
2016-02-15  16.600431   2.069971
2016-03-15  15.686425   8.070430
2016-04-15  17.726111  10.535556
2016-05-15  17.375403  15.874462
2016-06-15  22.536111  21.462639
2016-07-15  24.541532  24.767608
2016-08-15  23.983199  25.351882
2016-09-15  22.379306  21.032778
2016-10-15  16.137903  14.321640
2016-11-15  17.196111   8.539722
2016-12-15  13.390457   2.327285

In [72]:
temp.resample("QE").mean() # use QE instead of Q

                   LA         NY
datetime
2013-03-31  13.099212   1.862361
2013-06-30  18.472115  16.245101
2013-09-30  21.999638  22.411594
2013-12-31  15.047781   8.084918
2014-03-31  15.508287  -0.570880
2014-06-30  18.891255  16.253938
2014-09-30  22.281295  21.738315
2014-12-31  12.281748   7.855933
2015-03-31  11.869306  -3.340509
2015-06-30  16.334386  16.445238
2015-09-30  24.105571  23.314810
2015-12-31  16.331839  10.482745
2016-03-31  14.895375   3.466484
2016-06-30  19.192353  15.956639
2016-09-30  23.648324  23.746603
2016-12-31  15.557201   8.394656

In [73]:
temp.resample("QE-FEB").mean() # use QE-FEB instead of QE-Feb

                   LA         NY
datetime
2013-02-28  12.066525   0.886723
2013-05-31  16.859973  10.074230
2013-08-31  21.184601  23.694384
2013-11-30  18.028755  13.258288
2014-02-28  14.675000  -0.301713
2014-05-31  17.562047   9.645652
2014-08-31  21.691168  22.559284
2014-11-30  16.640522  13.097070
2015-02-28   9.822593  -2.481574
2015-05-31  14.185054   9.975181
2015-08-31  22.934511  22.909692
2015-11-30  20.556090  14.764515
2016-02-29  13.612225   3.668178
2016-05-31  16.920652  11.503895
2016-08-31  23.699457  23.886775
2016-11-30  18.544368  14.627976
2017-02-28  13.390457   2.327285

In [74]:
temp.resample("YE").mean() # use YE instead of A

                   LA         NY
datetime
2013-12-31  17.174229  12.196153
2014-12-31  17.245616  11.370959
2015-12-31  17.191530  11.795194
2016-12-31  18.330305  12.908470

In [75]:
temp.resample("YS").mean() # use YS instead of AS

                   LA         NY
datetime
2013-01-01  17.174229  12.196153
2014-01-01  17.245616  11.370959
2015-01-01  17.191530  11.795194
2016-01-01  18.330305  12.908470