# Advanced Topics

## Importing Financial Data from Excel

In [2]:
import pandas as pd

In [3]:
pd.read_excel("SP500.xls").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12107 entries, 0 to 12106
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       12107 non-null  datetime64[ns]
 1   Open       12107 non-null  float64
 2   High       12107 non-null  float64
 3   Low        12107 non-null  float64
 4   Close      12107 non-null  float64
 5   Adj Close  12107 non-null  float64
 6   Volume     12107 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 662.2 KB

In [4]:
pd.read_excel("SP500.xls", parse_dates= ["Date"], index_col = "Date")

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1970-12-31,92.269997,92.790001,91.360001,92.150002,92.150002,13390000
1971-01-04,92.150002,92.190002,90.639999,91.150002,91.150002,10010000
1971-01-05,91.150002,92.279999,90.690002,91.800003,91.800003,12600000
1971-01-06,91.800003,93.000000,91.500000,92.349998,92.349998,16960000
1971-01-07,92.349998,93.260002,91.750000,92.379997,92.379997,16460000
...,...,...,...,...,...,...
2018-12-21,2465.379883,2504.409912,2408.550049,2416.620117,2416.620117,-980924592
2018-12-24,2400.560059,2410.340088,2351.100098,2351.100098,2351.100098,-1681037296
2018-12-26,2363.120117,2467.760010,2346.580078,2467.699951,2467.699951,-60977296
2018-12-27,2442.500000,2489.100098,2397.939941,2488.830078,2488.830078,-198357296
2018-12-28,2498.770020,2520.270020,2472.889893,2485.739990,2485.739990,-592347296

In [5]:
pd.read_excel("SP500.xls", parse_dates= ["Date"], index_col = "Date", usecols = "A, C:E")

                   High          Low        Close
Date
1970-12-31    92.790001    91.360001    92.150002
1971-01-04    92.190002    90.639999    91.150002
1971-01-05    92.279999    90.690002    91.800003
1971-01-06    93.000000    91.500000    92.349998
1971-01-07    93.260002    91.750000    92.379997
...                 ...          ...          ...
2018-12-21  2504.409912  2408.550049  2416.620117
2018-12-24  2410.340088  2351.100098  2351.100098
2018-12-26  2467.760010  2346.580078  2467.699951
2018-12-27  2489.100098  2397.939941  2488.830078
2018-12-28  2520.270020  2472.889893  2485.739990

[12107 rows x 3 columns]

In [6]:
pd.read_excel("SP500.xls", sheet_name= "Sales")

  Unnamed: 0      City  Sales
0       Mike  New York     25
1        Jim    Boston     43
2     Steven    London     76
3        Joe    Madrid     12
4        Tom     Paris     89

In [7]:
SP500 = pd.read_excel("SP500.xls", parse_dates= ["Date"], index_col = "Date", usecols= "A:E")

In [8]:
SP500.head()

                 Open       High        Low      Close
Date
1970-12-31  92.269997  92.790001  91.360001  92.150002
1971-01-04  92.150002  92.190002  90.639999  91.150002
1971-01-05  91.150002  92.279999  90.690002  91.800003
1971-01-06  91.800003  93.000000  91.500000  92.349998
1971-01-07  92.349998  93.260002  91.750000  92.379997

In [9]:
SP500.tail()

                   Open         High          Low        Close
Date
2018-12-21  2465.379883  2504.409912  2408.550049  2416.620117
2018-12-24  2400.560059  2410.340088  2351.100098  2351.100098
2018-12-26  2363.120117  2467.760010  2346.580078  2467.699951
2018-12-27  2442.500000  2489.100098  2397.939941  2488.830078
2018-12-28  2498.770020  2520.270020  2472.889893  2485.739990

In [10]:
SP500.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 12107 entries, 1970-12-31 to 2018-12-28
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    12107 non-null  float64
 1   High    12107 non-null  float64
 2   Low     12107 non-null  float64
 3   Close   12107 non-null  float64
dtypes: float64(4)
memory usage: 472.9 KB

In [11]:
SP500.to_csv("SP500.csv")

In [12]:
SP500.to_excel("SP500_red.xls", engine = "openpyxl")

### Merging Time Series

In [13]:
import pandas as pd

In [14]:
stocks = pd.read_csv("stocks.csv", header = [0,1], index_col= [0], parse_dates= [0]).Close

In [15]:
stocks.head()

                AAPL         BA    DIS         IBM         KO       MSFT
Date
2009-12-31  7.526072  54.130001  32.25  130.899994  28.500000  30.480000
2010-01-04  7.643214  56.180000  32.07  132.449997  28.520000  30.950001
2010-01-05  7.656428  58.020000  31.99  130.850006  28.174999  30.959999
2010-01-06  7.534643  59.779999  31.82  130.000000  28.165001  30.770000
2010-01-07  7.520714  62.200001  31.83  129.550003  28.094999  30.450001

In [16]:
aapl = stocks.loc["2010-01-01" : "2014-12-31", "AAPL"].to_frame()
aapl.head()

                AAPL
Date
2010-01-04  7.643214
2010-01-05  7.656428
2010-01-06  7.534643
2010-01-07  7.520714
2010-01-08  7.570714

In [17]:
ba = stocks.loc["2012-01-01" : "2016-12-31", "BA"].to_frame()
ba.head()

                   BA
Date
2012-01-03  74.220001
2012-01-04  74.330002
2012-01-05  73.529999
2012-01-06  73.980003
2012-01-09  74.529999

In [18]:
aapl["BA"] = ba.BA

In [19]:
aapl.head()

                AAPL  BA
Date
2010-01-04  7.643214 NaN
2010-01-05  7.656428 NaN
2010-01-06  7.534643 NaN
2010-01-07  7.520714 NaN
2010-01-08  7.570714 NaN

In [20]:
aapl.tail()

                 AAPL          BA
Date
2014-12-24  28.002501  131.240005
2014-12-26  28.497499  131.630005
2014-12-29  28.477501  132.289993
2014-12-30  28.129999  131.830002
2014-12-31  27.594999  129.979996

In [21]:
aapl.dropna()

                 AAPL          BA
Date
2012-01-03  14.686786   74.220001
2012-01-04  14.765715   74.330002
2012-01-05  14.929643   73.529999
2012-01-06  15.085714   73.980003
2012-01-09  15.061786   74.529999
...               ...         ...
2014-12-24  28.002501  131.240005
2014-12-26  28.497499  131.630005
2014-12-29  28.477501  132.289993
2014-12-30  28.129999  131.830002
2014-12-31  27.594999  129.979996

[754 rows x 2 columns]

In [22]:
ba.reindex(aapl.index).dropna()

                    BA
Date
2012-01-03   74.220001
2012-01-04   74.330002
2012-01-05   73.529999
2012-01-06   73.980003
2012-01-09   74.529999
...                ...
2014-12-24  131.240005
2014-12-26  131.630005
2014-12-29  132.289993
2014-12-30  131.830002
2014-12-31  129.979996

[754 rows x 1 columns]

In [23]:
dis = stocks.loc["2010-01-01" : "2016-12-31", "DIS"].resample("W-Fri").last().to_frame()
dis.head()

                  DIS
Date
2010-01-08  31.879999
2010-01-15  30.600000
2010-01-22  29.980000
2010-01-29  29.549999
2010-02-05  29.540001

In [24]:
aapl.head()

                AAPL  BA
Date
2010-01-04  7.643214 NaN
2010-01-05  7.656428 NaN
2010-01-06  7.534643 NaN
2010-01-07  7.520714 NaN
2010-01-08  7.570714 NaN

In [25]:
aapl["DIS"] = dis.DIS

In [26]:
aapl.head(10)

                AAPL  BA        DIS
Date
2010-01-04  7.643214 NaN        NaN
2010-01-05  7.656428 NaN        NaN
2010-01-06  7.534643 NaN        NaN
2010-01-07  7.520714 NaN        NaN
2010-01-08  7.570714 NaN  31.879999
2010-01-11  7.503929 NaN        NaN
2010-01-12  7.418571 NaN        NaN
2010-01-13  7.523214 NaN        NaN
2010-01-14  7.479643 NaN        NaN
2010-01-15  7.354643 NaN  30.600000

In [27]:
dis.reindex(aapl.index)

                  DIS
Date
2010-01-04        NaN
2010-01-05        NaN
2010-01-06        NaN
2010-01-07        NaN
2010-01-08  31.879999
...               ...
2014-12-24        NaN
2014-12-26  95.029999
2014-12-29        NaN
2014-12-30        NaN
2014-12-31        NaN

[1258 rows x 1 columns]

In [28]:
dis["AAPL"] = aapl.AAPL

In [29]:
dis.head(10)

                  DIS      AAPL
Date
2010-01-08  31.879999  7.570714
2010-01-15  30.600000  7.354643
2010-01-22  29.980000  7.062500
2010-01-29  29.549999  6.859286
2010-02-05  29.540001  6.980714
2010-02-12  30.070000  7.156428
2010-02-19  31.230000  7.202500
2010-02-26  31.240000  7.307857
2010-03-05  33.220001  7.819643
2010-03-12  33.689999  8.092857

## Helpful DatetimeIndex Attributes and Methods

In [30]:
import pandas as pd

In [31]:
stocks = pd.read_csv("stocks.csv", header = [0,1], index_col= [0], parse_dates= [0])

In [32]:
stocks.head()

           Adj Close                                                         \
                AAPL         BA        DIS        IBM         KO       MSFT
Date
2009-12-31  6.503574  41.856789  28.090706  92.406113  18.951757  23.801456
2010-01-04  6.604801  43.441975  27.933924  93.500313  18.965061  24.168472
2010-01-05  6.616219  44.864773  27.864237  92.370834  18.735643  24.176279
2010-01-06  6.510980  46.225727  27.716166  91.770790  18.728989  24.027906
2010-01-07  6.498945  48.097031  27.724878  91.453102  18.682440  23.778025

               Close                                ...   Open              \
                AAPL         BA    DIS         IBM  ...    DIS         IBM
Date                                                ...
2009-12-31  7.526072  54.130001  32.25  130.899994  ...  32.27  132.410004
2010-01-04  7.643214  56.180000  32.07  132.449997  ...  32.50  131.179993
2010-01-05  7.656428  58.020000  31.99  130.850006  ...  32.07  131.679993
2010-01-06  7.534643  59.779999  31.82  130.000000  ...  31.90  130.679993
2010-01-07  7.520714  62.200001  31.83  129.550003  ...  31.77  129.869995

                                     Volume                               \
                   KO       MSFT       AAPL        BA       DIS      IBM
Date
2009-12-31  28.790001  30.980000  352410800   2189400  19651700  4223400
2010-01-04  28.580000  30.620001  493729600   6186700  13700400  6155300
2010-01-05  28.424999  30.850000  601904800   8867800  10307700  6841400
2010-01-06  28.174999  30.879999  552160000   8836500  10709500  5605300
2010-01-07  28.165001  30.629999  477131200  14379100   8202100  5840600


                  KO      MSFT
Date
2009-12-31  10848800  31929700
2010-01-04  13870400  38409100
2010-01-05  23172400  49749600
2010-01-06  19264600  58182400
2010-01-07  13234600  50559700

[5 rows x 36 columns]

In [33]:
close = stocks.loc[:, "Close"].copy()

In [34]:
close.head()

                AAPL         BA    DIS         IBM         KO       MSFT
Date
2009-12-31  7.526072  54.130001  32.25  130.899994  28.500000  30.480000
2010-01-04  7.643214  56.180000  32.07  132.449997  28.520000  30.950001
2010-01-05  7.656428  58.020000  31.99  130.850006  28.174999  30.959999
2010-01-06  7.534643  59.779999  31.82  130.000000  28.165001  30.770000
2010-01-07  7.520714  62.200001  31.83  129.550003  28.094999  30.450001

In [35]:
close.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2289 entries, 2009-12-31 to 2019-02-05
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2289 non-null   float64
 1   BA      2289 non-null   float64
 2   DIS     2289 non-null   float64
 3   IBM     2289 non-null   float64
 4   KO      2289 non-null   float64
 5   MSFT    2289 non-null   float64
dtypes: float64(6)
memory usage: 125.2 KB

In [36]:
close.index

DatetimeIndex(['2009-12-31', '2010-01-04', '2010-01-05', '2010-01-06',
               '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
               '2010-01-13', '2010-01-14',
               ...
               '2019-01-23', '2019-01-24', '2019-01-25', '2019-01-28',
               '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01',
               '2019-02-04', '2019-02-05'],
              dtype='datetime64[ns]', name='Date', length=2289, freq=None)

In [37]:
close.index.day

Index([31,  4,  5,  6,  7,  8, 11, 12, 13, 14,
       ...
       23, 24, 25, 28, 29, 30, 31,  1,  4,  5],
      dtype='int32', name='Date', length=2289)

In [38]:
close.index.month

Index([12,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       ...
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2],
      dtype='int32', name='Date', length=2289)

In [39]:
close.index.year

Index([2009, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010,
       ...
       2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019],
      dtype='int32', name='Date', length=2289)

In [40]:
close.index.day_name()

Index(['Thursday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
       'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       ...
       'Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday', 'Friday', 'Monday', 'Tuesday'],
      dtype='object', name='Date', length=2289)

In [41]:
close.index.month_name()

Index(['December', 'January', 'January', 'January', 'January', 'January',
       'January', 'January', 'January', 'January',
       ...
       'January', 'January', 'January', 'January', 'January', 'January',
       'January', 'February', 'February', 'February'],
      dtype='object', name='Date', length=2289)

In [42]:
close.index.weekday

Index([3, 0, 1, 2, 3, 4, 0, 1, 2, 3,
       ...
       2, 3, 4, 0, 1, 2, 3, 4, 0, 1],
      dtype='int32', name='Date', length=2289)

In [43]:
close.index.quarter

Index([4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       ...
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype='int32', name='Date', length=2289)

In [44]:
close.index.days_in_month

Index([31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       ...
       31, 31, 31, 31, 31, 31, 31, 28, 28, 28],
      dtype='int32', name='Date', length=2289)

In [45]:
# close.index.week # old

In [46]:
# close.index.weekofyear #old

In [47]:
close.index.isocalendar().week #new

Date
2009-12-31    53
2010-01-04     1
2010-01-05     1
2010-01-06     1
2010-01-07     1
              ..
2019-01-30     5
2019-01-31     5
2019-02-01     5
2019-02-04     6
2019-02-05     6
Name: week, Length: 2289, dtype: UInt32

In [48]:
close.index.is_month_end

array([ True, False, False, ..., False, False, False], shape=(2289,))

In [49]:
close["Day"] = stocks.index.day_name()
close["Quarter"] = stocks.index.quarter

In [50]:
close.head()

,AAPL,BA,DIS,IBM,KO,MSFT,Day,Quarter
Date,,,,,,,,
2009-12-31,7.526072,54.130001,32.25,130.899994,28.500000,30.480000,Thursday,4
2010-01-04,7.643214,56.180000,32.07,132.449997,28.520000,30.950001,Monday,1
2010-01-05,7.656428,58.020000,31.99,130.850006,28.174999,30.959999,Tuesday,1
2010-01-06,7.534643,59.779999,31.82,130.000000,28.165001,30.770000,Wednesday,1
2010-01-07,7.520714,62.200001,31.83,129.550003,28.094999,30.450001,Thursday,1

## Filling NA Values with bfill, ffill and interpolation

In [51]:
close.head()

,AAPL,BA,DIS,IBM,KO,MSFT,Day,Quarter
Date,,,,,,,,
2009-12-31,7.526072,54.130001,32.25,130.899994,28.500000,30.480000,Thursday,4
2010-01-04,7.643214,56.180000,32.07,132.449997,28.520000,30.950001,Monday,1
2010-01-05,7.656428,58.020000,31.99,130.850006,28.174999,30.959999,Tuesday,1
2010-01-06,7.534643,59.779999,31.82,130.000000,28.165001,30.770000,Wednesday,1
2010-01-07,7.520714,62.200001,31.83,129.550003,28.094999,30.450001,Thursday,1

In [52]:
close.tail()

,AAPL,BA,DIS,IBM,KO,MSFT,Day,Quarter
Date,,,,,,,,
2019-01-30,41.312500,387.720001,110.129997,134.380005,47.860001,106.379997,Wednesday,1
2019-01-31,41.610001,385.619995,111.519997,134.419998,48.130001,104.430000,Thursday,1
2019-02-01,41.630001,387.429993,111.300003,134.100006,48.700001,102.779999,Friday,1
2019-02-04,42.812500,397.000000,111.800003,135.190002,49.250000,105.739998,Monday,1
2019-02-05,43.544998,410.179993,112.660004,135.550003,49.259998,107.220001,Tuesday,1

In [68]:
all_days = pd.date_range(start = "2009-12-31", end = "2019-02-06", freq = "D")
all_days

DatetimeIndex(['2009-12-31', '2010-01-01', '2010-01-02', '2010-01-03',
               '2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
               '2010-01-08', '2010-01-09',
               ...
               '2019-01-28', '2019-01-29', '2019-01-30', '2019-01-31',
               '2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04',
               '2019-02-05', '2019-02-06'],
              dtype='datetime64[ns]', length=3325, freq='D')

In [69]:
close = close.reindex(all_days)

In [70]:
close.head(20)

,AAPL,BA,DIS,IBM,KO,MSFT,Day,Quarter
2009-12-31,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Thursday,4
2010-01-01,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Friday,1
2010-01-02,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Saturday,1
2010-01-03,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Sunday,1
2010-01-04,7.643214,56.180000,32.070000,132.449997,28.520000,30.950001,Monday,1
2010-01-05,7.656428,58.020000,31.990000,130.850006,28.174999,30.959999,Tuesday,1
2010-01-06,7.534643,59.779999,31.820000,130.000000,28.165001,30.770000,Wednesday,1
2010-01-07,7.520714,62.200001,31.830000,129.550003,28.094999,30.450001,Thursday,1
2010-01-08,7.570714,61.599998,31.879999,130.850006,27.575001,30.660000,Friday,1
2010-01-09,7.570714,61.599998,31.879999,130.850006,27.575001,30.660000,Saturday,1
2010-01-10,7.570714,61.599998,31.879999,130.850006,27.575001,30.660000,Sunday,1
2010-01-11,7.503929,60.869999,31.360001,129.479996,28.135000,30.270000,Monday,1
2010-01-12,7.418571,60.430000,30.820000,130.509995,28.440001,30.070000,Tuesday,1
2010-01-13,7.523214,61.160000,31.290001,130.229996,28.514999,30.350000,Wednesday,1
2010-01-14,7.479643,61.560001,31.020000,132.309998,28.565001,30.959999,Thursday,1
2010-01-15,7.354643,60.820000,30.600000,131.779999,28.145000,30.860001,Friday,1
2010-01-16,7.354643,60.820000,30.600000,131.779999,28.145000,30.860001,Saturday,1
2010-01-17,7.354643,60.820000,30.600000,131.779999,28.145000,30.860001,Sunday,1
2010-01-18,7.354643,60.820000,30.600000,131.779999,28.145000,30.860001,Monday,1
2010-01-19,7.680000,60.650002,31.010000,134.139999,28.209999,31.100000,Tuesday,1

In [56]:
close.Day = close.index.day_name()
close.Quarter = close.index.quarter

In [ ]:
# close.fillna(method = "ffill", inplace= True) # old

In [ ]:
close.ffillna(inplace= True) # new

In [63]:
close.head(15)

,AAPL,BA,DIS,IBM,KO,MSFT,Day,Quarter
2009-12-31,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Thursday,4
2010-01-01,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Friday,1
2010-01-02,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Saturday,1
2010-01-03,7.526072,54.130001,32.250000,130.899994,28.500000,30.480000,Sunday,1
2010-01-04,7.643214,56.180000,32.070000,132.449997,28.520000,30.950001,Monday,1
2010-01-05,7.656428,58.020000,31.990000,130.850006,28.174999,30.959999,Tuesday,1
2010-01-06,7.534643,59.779999,31.820000,130.000000,28.165001,30.770000,Wednesday,1
2010-01-07,7.520714,62.200001,31.830000,129.550003,28.094999,30.450001,Thursday,1
2010-01-08,7.570714,61.599998,31.879999,130.850006,27.575001,30.660000,Friday,1
2010-01-09,7.570714,61.599998,31.879999,130.850006,27.575001,30.660000,Saturday,1
2010-01-10,7.570714,61.599998,31.879999,130.850006,27.575001,30.660000,Sunday,1
2010-01-11,7.503929,60.869999,31.360001,129.479996,28.135000,30.270000,Monday,1
2010-01-12,7.418571,60.430000,30.820000,130.509995,28.440001,30.070000,Tuesday,1
2010-01-13,7.523214,61.160000,31.290001,130.229996,28.514999,30.350000,Wednesday,1
2010-01-14,7.479643,61.560001,31.020000,132.309998,28.565001,30.959999,Thursday,1

In [71]:
temp = pd.read_csv("temp.csv", parse_dates=["datetime"], index_col = "datetime")

In [72]:
temp.head(10)

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3
2013-01-01 05:00:00   8.7 -2.5
2013-01-01 06:00:00   6.9 -3.2
2013-01-01 07:00:00   7.8 -3.4
2013-01-01 08:00:00   6.7 -3.0
2013-01-01 09:00:00   6.6 -1.8

In [73]:
temp = temp.resample("30 Min").mean()
temp.head(10)

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 00:30:00   NaN  NaN
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 01:30:00   NaN  NaN
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 02:30:00   NaN  NaN
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 03:30:00   NaN  NaN
2013-01-01 04:00:00   8.8 -2.3
2013-01-01 04:30:00   NaN  NaN

In [74]:
temp.interpolate()

                        LA    NY
datetime
2013-01-01 00:00:00  11.70 -1.10
2013-01-01 00:30:00  11.20 -1.40
2013-01-01 01:00:00  10.70 -1.70
2013-01-01 01:30:00  10.30 -1.85
2013-01-01 02:00:00   9.90 -2.00
...                    ...   ...
2016-12-31 21:00:00  12.80  5.80
2016-12-31 21:30:00  12.55  5.75
2016-12-31 22:00:00  12.30  5.70
2016-12-31 22:30:00  12.10  5.60
2016-12-31 23:00:00  11.90  5.50

[70127 rows x 2 columns]

## Timezones and Converting (Part 1)

In [2]:
import pandas as pd

In [3]:
ge = pd.read_csv("GE_prices.csv", parse_dates= ["date"], index_col= "date")

In [4]:
ge.head(30)

                     1. open  2. high   3. low  4. close   5. volume
date
2019-07-29 10:00:00  10.5000  10.5800  10.4300   10.4400   4840329.0
2019-07-29 10:30:00  10.4404  10.4847  10.3997   10.4104   3860280.0
2019-07-29 11:00:00  10.4200  10.5000  10.4100   10.5000   1912153.0
2019-07-29 11:30:00  10.4931  10.5300  10.4800   10.4850   1916453.0
2019-07-29 12:00:00  10.4900  10.5000  10.4400   10.4500   2467638.0
2019-07-29 12:30:00  10.4453  10.4652  10.4001   10.4153   3239894.0
2019-07-29 13:00:00  10.4200  10.4500  10.4100   10.4400   1357248.0
2019-07-29 13:30:00  10.4319  10.4701  10.4300   10.4554   2030041.0
2019-07-29 14:00:00  10.4600  10.4600  10.4100   10.4200   1171359.0
2019-07-29 14:30:00  10.4204  10.4500  10.4100   10.4349   1041398.0
2019-07-29 15:00:00  10.4400  10.4400  10.3900   10.4200   1553265.0
2019-07-29 15:30:00  10.4200  10.4250  10.4000   10.4050   1207811.0
2019-07-29 16:00:00  10.4100  10.4100  10.3800   10.3800   5649305.0
2019-07-30 10:00:00  10.3900  10.4200  10.2800   10.3600   6309034.0
2019-07-30 10:30:00  10.3553  10.3801  10.3200   10.3383   3808618.0
2019-07-30 11:00:00  10.3400  10.3900  10.3300   10.3400   2254152.0
2019-07-30 11:30:00  10.3441  10.4400  10.3400   10.4131   2247660.0
2019-07-30 12:00:00  10.4200  10.4400  10.4000   10.4200   2309264.0
2019-07-30 12:30:00  10.4204  10.4800  10.4000   10.4554   2849662.0
2019-07-30 13:00:00  10.4600  10.4700  10.4400   10.4600   1265244.0
2019-07-30 13:30:00  10.4560  10.4700  10.4500   10.4550   1635434.0
2019-07-30 14:00:00  10.4600  10.4900  10.4500   10.4900   1266372.0
2019-07-30 14:30:00  10.4900  10.5200  10.4900   10.5100   2487611.0
2019-07-30 15:00:00  10.5100  10.5600  10.5000   10.5200   3757587.0
2019-07-30 15:30:00  10.5199  10.5300  10.4900   10.4900   2755634.0
2019-07-30 16:00:00  10.4900  10.5800  10.4700   10.5100   8944676.0
2019-07-31 10:00:00  10.6400  10.7900  10.3700   10.4800  42669453.0
2019-07-31 10:30:00  10.4854  10.5101  10.0597   10.0904  16983457.0
2019-07-31 11:00:00  10.1000  10.1900  10.0500   10.0600  12682783.0
2019-07-31 11:30:00  10.0650  10.2700  10.0600   10.2200  10973783.0

In [5]:
ge.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 389 entries, 2019-07-29 10:00:00 to 2019-09-09 16:00:00
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   1. open    389 non-null    float64
 1   2. high    389 non-null    float64
 2   3. low     389 non-null    float64
 3   4. close   389 non-null    float64
 4   5. volume  389 non-null    float64
dtypes: float64(5)
memory usage: 18.2 KB

In [6]:
ge.index

DatetimeIndex(['2019-07-29 10:00:00', '2019-07-29 10:30:00',
               '2019-07-29 11:00:00', '2019-07-29 11:30:00',
               '2019-07-29 12:00:00', '2019-07-29 12:30:00',
               '2019-07-29 13:00:00', '2019-07-29 13:30:00',
               '2019-07-29 14:00:00', '2019-07-29 14:30:00',
               ...
               '2019-09-09 11:30:00', '2019-09-09 12:00:00',
               '2019-09-09 12:30:00', '2019-09-09 13:00:00',
               '2019-09-09 13:30:00', '2019-09-09 14:00:00',
               '2019-09-09 14:30:00', '2019-09-09 15:00:00',
               '2019-09-09 15:30:00', '2019-09-09 16:00:00'],
              dtype='datetime64[ns]', name='date', length=389, freq=None)

In [7]:
print(ge.index.tz)

None

In [8]:
ge.tz_localize("UTC")

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 10:00:00+00:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 10:30:00+00:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 11:00:00+00:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 11:30:00+00:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 12:00:00+00:00  10.4900  10.5000  10.4400   10.4500  2467638.0
...                            ...      ...      ...       ...        ...
2019-09-09 14:00:00+00:00   8.9900   8.9950   8.9700    8.9800  1740722.0
2019-09-09 14:30:00+00:00   8.9735   9.0000   8.9700    8.9835  1412823.0
2019-09-09 15:00:00+00:00   8.9900   9.0100   8.9350    8.9500  4177838.0
2019-09-09 15:30:00+00:00   8.9453   8.9700   8.9300    8.9603  2254279.0
2019-09-09 16:00:00+00:00   8.9600   8.9900   8.9200    8.9700  6887530.0

[389 rows x 5 columns]

In [9]:
ge.tz_localize("America/New_York")

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 10:00:00-04:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 10:30:00-04:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 11:00:00-04:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 11:30:00-04:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 12:00:00-04:00  10.4900  10.5000  10.4400   10.4500  2467638.0
...                            ...      ...      ...       ...        ...
2019-09-09 14:00:00-04:00   8.9900   8.9950   8.9700    8.9800  1740722.0
2019-09-09 14:30:00-04:00   8.9735   9.0000   8.9700    8.9835  1412823.0
2019-09-09 15:00:00-04:00   8.9900   9.0100   8.9350    8.9500  4177838.0
2019-09-09 15:30:00-04:00   8.9453   8.9700   8.9300    8.9603  2254279.0
2019-09-09 16:00:00-04:00   8.9600   8.9900   8.9200    8.9700  6887530.0

[389 rows x 5 columns]

In [10]:
ge = ge.tz_localize("America/New_York")

In [11]:
ge.head()

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 10:00:00-04:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 10:30:00-04:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 11:00:00-04:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 11:30:00-04:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 12:00:00-04:00  10.4900  10.5000  10.4400   10.4500  2467638.0

## Timezones and Converting (Part 2)

In [12]:
ge.index.tz

In [13]:
ge.tz_convert("UTC")

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 14:00:00+00:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 14:30:00+00:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 15:00:00+00:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 15:30:00+00:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 16:00:00+00:00  10.4900  10.5000  10.4400   10.4500  2467638.0
...                            ...      ...      ...       ...        ...
2019-09-09 18:00:00+00:00   8.9900   8.9950   8.9700    8.9800  1740722.0
2019-09-09 18:30:00+00:00   8.9735   9.0000   8.9700    8.9835  1412823.0
2019-09-09 19:00:00+00:00   8.9900   9.0100   8.9350    8.9500  4177838.0
2019-09-09 19:30:00+00:00   8.9453   8.9700   8.9300    8.9603  2254279.0
2019-09-09 20:00:00+00:00   8.9600   8.9900   8.9200    8.9700  6887530.0

[389 rows x 5 columns]

In [14]:
ge.tz_convert("America/Los_Angeles")

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 07:00:00-07:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 07:30:00-07:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 08:00:00-07:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 08:30:00-07:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 09:00:00-07:00  10.4900  10.5000  10.4400   10.4500  2467638.0
...                            ...      ...      ...       ...        ...
2019-09-09 11:00:00-07:00   8.9900   8.9950   8.9700    8.9800  1740722.0
2019-09-09 11:30:00-07:00   8.9735   9.0000   8.9700    8.9835  1412823.0
2019-09-09 12:00:00-07:00   8.9900   9.0100   8.9350    8.9500  4177838.0
2019-09-09 12:30:00-07:00   8.9453   8.9700   8.9300    8.9603  2254279.0
2019-09-09 13:00:00-07:00   8.9600   8.9900   8.9200    8.9700  6887530.0

[389 rows x 5 columns]

In [15]:
ge_la = ge.tz_convert("America/Los_Angeles")

In [16]:
ge_la.head()

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 07:00:00-07:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 07:30:00-07:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 08:00:00-07:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 08:30:00-07:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 09:00:00-07:00  10.4900  10.5000  10.4400   10.4500  2467638.0

In [17]:
ge.head()

                           1. open  2. high   3. low  4. close  5. volume
date
2019-07-29 10:00:00-04:00  10.5000  10.5800  10.4300   10.4400  4840329.0
2019-07-29 10:30:00-04:00  10.4404  10.4847  10.3997   10.4104  3860280.0
2019-07-29 11:00:00-04:00  10.4200  10.5000  10.4100   10.5000  1912153.0
2019-07-29 11:30:00-04:00  10.4931  10.5300  10.4800   10.4850  1916453.0
2019-07-29 12:00:00-04:00  10.4900  10.5000  10.4400   10.4500  2467638.0

In [18]:
comb = pd.concat([ge, ge_la], axis = 1)

In [19]:
comb.head()

,1. open,2. high,3. low,4. close,5. volume,1. open,2. high,3. low,4. close,5. volume
date,,,,,,,,,,
2019-07-29 14:00:00+00:00,10.5000,10.5800,10.4300,10.4400,4840329.0,10.5000,10.5800,10.4300,10.4400,4840329.0
2019-07-29 14:30:00+00:00,10.4404,10.4847,10.3997,10.4104,3860280.0,10.4404,10.4847,10.3997,10.4104,3860280.0
2019-07-29 15:00:00+00:00,10.4200,10.5000,10.4100,10.5000,1912153.0,10.4200,10.5000,10.4100,10.5000,1912153.0
2019-07-29 15:30:00+00:00,10.4931,10.5300,10.4800,10.4850,1916453.0,10.4931,10.5300,10.4800,10.4850,1916453.0
2019-07-29 16:00:00+00:00,10.4900,10.5000,10.4400,10.4500,2467638.0,10.4900,10.5000,10.4400,10.4500,2467638.0

In [20]:
comb.index

DatetimeIndex(['2019-07-29 14:00:00+00:00', '2019-07-29 14:30:00+00:00',
               '2019-07-29 15:00:00+00:00', '2019-07-29 15:30:00+00:00',
               '2019-07-29 16:00:00+00:00', '2019-07-29 16:30:00+00:00',
               '2019-07-29 17:00:00+00:00', '2019-07-29 17:30:00+00:00',
               '2019-07-29 18:00:00+00:00', '2019-07-29 18:30:00+00:00',
               ...
               '2019-09-09 15:30:00+00:00', '2019-09-09 16:00:00+00:00',
               '2019-09-09 16:30:00+00:00', '2019-09-09 17:00:00+00:00',
               '2019-09-09 17:30:00+00:00', '2019-09-09 18:00:00+00:00',
               '2019-09-09 18:30:00+00:00', '2019-09-09 19:00:00+00:00',
               '2019-09-09 19:30:00+00:00', '2019-09-09 20:00:00+00:00'],
              dtype='datetime64[ns, UTC]', name='date', length=389, freq=None)

In [21]:
comb["NY_time"] = comb.index.tz_convert("America/New_York")
comb["LA_time"] = comb.index.tz_convert("America/Los_Angeles")

In [22]:
comb.head()

,1. open,2. high,3. low,4. close,5. volume,1. open,2. high,3. low,4. close,5. volume,NY_time,LA_time
date,,,,,,,,,,,,
2019-07-29 14:00:00+00:00,10.5000,10.5800,10.4300,10.4400,4840329.0,10.5000,10.5800,10.4300,10.4400,4840329.0,2019-07-29 10:00:00-04:00,2019-07-29 07:00:00-07:00
2019-07-29 14:30:00+00:00,10.4404,10.4847,10.3997,10.4104,3860280.0,10.4404,10.4847,10.3997,10.4104,3860280.0,2019-07-29 10:30:00-04:00,2019-07-29 07:30:00-07:00
2019-07-29 15:00:00+00:00,10.4200,10.5000,10.4100,10.5000,1912153.0,10.4200,10.5000,10.4100,10.5000,1912153.0,2019-07-29 11:00:00-04:00,2019-07-29 08:00:00-07:00
2019-07-29 15:30:00+00:00,10.4931,10.5300,10.4800,10.4850,1916453.0,10.4931,10.5300,10.4800,10.4850,1916453.0,2019-07-29 11:30:00-04:00,2019-07-29 08:30:00-07:00
2019-07-29 16:00:00+00:00,10.4900,10.5000,10.4400,10.4500,2467638.0,10.4900,10.5000,10.4400,10.4500,2467638.0,2019-07-29 12:00:00-04:00,2019-07-29 09:00:00-07:00

In [23]:
import pytz

In [24]:
len(pytz.all_timezones)

597

In [25]:
pytz.common_timezones

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'America/Anguilla', 'America/Antigua', 'America/Araguaina', 'America/Argentina/Buenos_Aires', 'America/Argentina/Catamarca', 'America/Argentina/Cordoba', 'America/Argentina/Jujuy', 'America/Argentina/La_Rioja', 'America/Argentina/Mendoza', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Aruba', 'America/Asuncion', 'America/Atikokan', 'America/Bahia', 'America/Bahia_Banderas', 'America/Barbados', 'America/Belem', 'America/Belize', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Bogota', 'America/Boise', 'America/Cambridge_Bay', 'America/Campo_Grande', 'America/Cancun', 'America/Caracas', 'America/Cayenne', 'America/Cayman', 'America/Chicago', 'America/Chihuahua', 'America/Ciudad_Juarez', 'America/Costa_Rica', 'America/Coyhaique', 'America/Creston', 'America/Cuiaba', 'America/Curacao', 'America/Danmarkshavn', 'America/Dawson', 'America/Dawson_Creek', 'America/Denver', 'America/Detroit', 'America/Dominica', 'America/Edmonton', 'America/Eirunepe', 'America/El_Salvador', 'America/Fort_Nelson', 'America/Fortaleza', 'America/Glace_Bay', 'America/Goose_Bay', 'America/Grand_Turk', 'America/Grenada', 'America/Guadeloupe', 'America/Guatemala', 'America/Guayaquil', 'America/Guyana', 'America/Halifax', 'America/Havana', 'America/Hermosillo', 'America/Indiana/Indianapolis', 'America/Indiana/Knox', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Tell_City', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Inuvik', 'America/Iqaluit', 'America/Jamaica', 'America/Juneau', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Kralendijk', 'America/La_Paz', 'America/Lima', 'America/Los_Angeles', 'America/Lower_Princes', 'America/Maceio', 'America/Managua', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Matamoros', 'America/Mazatlan', 'America/Menominee', 'America/Merida', 'America/Metlakatla', 'America/Mexico_City', 'America/Miquelon', 'America/Moncton', 'America/Monterrey', 'America/Montevideo', 'America/Montserrat', 'America/Nassau', 'America/New_York', 'America/Nome', 'America/Noronha', 'America/North_Dakota/Beulah', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/Nuuk', 'America/Ojinaga', 'America/Panama', 'America/Paramaribo', 'America/Phoenix', 'America/Port-au-Prince', 'America/Port_of_Spain', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Punta_Arenas', 'America/Rankin_Inlet', 'America/Recife', 'America/Regina', 'America/Resolute', 'America/Rio_Branco', 'America/Santarem', 'America/Santiago', 'America/Santo_Domingo', 'America/Sao_Paulo', 'America/Scoresbysund', 'America/Sitka', 'America/St_Barthelemy', 'America/St_Johns', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Thomas', 'America/St_Vincent', 'America/Swift_Current', 'America/Tegucigalpa', 'America/Thule', 'America/Tijuana', 'America/Toronto', 'America/Tortola', 'America/Vancouver', 'America/Whitehorse', 'America/Winnipeg', 'America/Yakutat', 'Antarctica/Casey', 'Antarctica/Davis', 'Antarctica/DumontDUrville', 'Antarctica/Macquarie', 'Antarctica/Mawson', 'Antarctica/McMurdo', 'Antarctica/Palmer', 'Antarctica/Rothera', 'Antarctica/Syowa', 'Antarctica/Troll', 'Antarctica/Vostok', 'Arctic/Longyearbyen', 'Asia/Aden', 'Asia/Almaty', 'Asia/Amman', 'Asia/Anadyr', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Atyrau', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Baku', 'Asia/Bangkok', 'Asia/Barnaul', 'Asia/Beirut', 'Asia/Bishkek', 'Asia/Brunei', 'Asia/Chita', 'Asia/Colombo', 'Asia/Damascus', 'Asia/Dhaka', 'Asia/Dili', 'Asia/Dubai', 'Asia/Dushanbe', 'Asia/Famagusta', 'Asia/Gaza', 'Asia/Hebron', 'Asia/Ho_Chi_Minh', 'Asia/Hong_Kong', 'Asia/Hovd', 'Asia/Irkutsk', 'Asia/Jakarta', 'Asia/Jayapura', 'Asia/Jerusalem', 'Asia/Kabul', 'Asia/Kamchatka', 'Asia/Karachi', 'Asia/Kathmandu', 'Asia/Khandyga', 'Asia/Kolkata', 'Asia/Krasnoyarsk', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Kuwait', 'Asia/Macau', 'Asia/Magadan', 'Asia/Makassar', 'Asia/Manila', 'Asia/Muscat', 'Asia/Nicosia', 'Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Oral', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Pyongyang', 'Asia/Qatar', 'Asia/Qostanay', 'Asia/Qyzylorda', 'Asia/Riyadh', 'Asia/Sakhalin', 'Asia/Samarkand', 'Asia/Seoul', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Srednekolymsk', 'Asia/Taipei', 'Asia/Tashkent', 'Asia/Tbilisi', 'Asia/Tehran', 'Asia/Thimphu', 'Asia/Tokyo', 'Asia/Tomsk', 'Asia/Ulaanbaatar', 'Asia/Urumqi', 'Asia/Ust-Nera', 'Asia/Vientiane', 'Asia/Vladivostok', 'Asia/Yakutsk', 'Asia/Yangon', 'Asia/Yekaterinburg', 'Asia/Yerevan', 'Atlantic/Azores', 'Atlantic/Bermuda', 'Atlantic/Canary', 'Atlantic/Cape_Verde', 'Atlantic/Faroe', 'Atlantic/Madeira', 'Atlantic/Reykjavik', 'Atlantic/South_Georgia', 'Atlantic/St_Helena', 'Atlantic/Stanley', 'Australia/Adelaide', 'Australia/Brisbane', 'Australia/Broken_Hill', 'Australia/Darwin', 'Australia/Eucla', 'Australia/Hobart', 'Australia/Lindeman', 'Australia/Lord_Howe', 'Australia/Melbourne', 'Australia/Perth', 'Australia/Sydney', 'Canada/Atlantic', 'Canada/Central', 'Canada/Eastern', 'Canada/Mountain', 'Canada/Newfoundland', 'Canada/Pacific', 'Europe/Amsterdam', 'Europe/Andorra', 'Europe/Astrakhan', 'Europe/Athens', 'Europe/Belgrade', 'Europe/Berlin', 'Europe/Bratislava', 'Europe/Brussels', 'Europe/Bucharest', 'Europe/Budapest', 'Europe/Busingen', 'Europe/Chisinau', 'Europe/Copenhagen', 'Europe/Dublin', 'Europe/Gibraltar', 'Europe/Guernsey', 'Europe/Helsinki', 'Europe/Isle_of_Man', 'Europe/Istanbul', 'Europe/Jersey', 'Europe/Kaliningrad', 'Europe/Kirov', 'Europe/Kyiv', 'Europe/Lisbon', 'Europe/Ljubljana', 'Europe/London', 'Europe/Luxembourg', 'Europe/Madrid', 'Europe/Malta', 'Europe/Mariehamn', 'Europe/Minsk', 'Europe/Monaco', 'Europe/Moscow', 'Europe/Oslo', 'Europe/Paris', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Riga', 'Europe/Rome', 'Europe/Samara', 'Europe/San_Marino', 'Europe/Sarajevo', 'Europe/Saratov', 'Europe/Simferopol', 'Europe/Skopje', 'Europe/Sofia', 'Europe/Stockholm', 'Europe/Tallinn', 'Europe/Tirane', 'Europe/Ulyanovsk', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Vilnius', 'Europe/Volgograd', 'Europe/Warsaw', 'Europe/Zagreb', 'Europe/Zurich', 'GMT', 'Indian/Antananarivo', 'Indian/Chagos', 'Indian/Christmas', 'Indian/Cocos', 'Indian/Comoro', 'Indian/Kerguelen', 'Indian/Mahe', 'Indian/Maldives', 'Indian/Mauritius', 'Indian/Mayotte', 'Indian/Reunion', 'Pacific/Apia', 'Pacific/Auckland', 'Pacific/Bougainville', 'Pacific/Chatham', 'Pacific/Chuuk', 'Pacific/Easter', 'Pacific/Efate', 'Pacific/Fakaofo', 'Pacific/Fiji', 'Pacific/Funafuti', 'Pacific/Galapagos', 'Pacific/Gambier', 'Pacific/Guadalcanal', 'Pacific/Guam', 'Pacific/Honolulu', 'Pacific/Kanton', 'Pacific/Kiritimati', 'Pacific/Kosrae', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Marquesas', 'Pacific/Midway', 'Pacific/Nauru', 'Pacific/Niue', 'Pacific/Norfolk', 'Pacific/Noumea', 'Pacific/Pago_Pago', 'Pacific/Palau', 'Pacific/Pitcairn', 'Pacific/Pohnpei', 'Pacific/Port_Moresby', 'Pacific/Rarotonga', 'Pacific/Saipan', 'Pacific/Tahiti', 'Pacific/Tarawa', 'Pacific/Tongatapu', 'Pacific/Wake', 'Pacific/Wallis', 'US/Alaska', 'US/Arizona', 'US/Central', 'US/Eastern', 'US/Hawaii', 'US/Mountain', 'US/Pacific', 'UTC']